### ISSUE TITLE
Add linting and autoformatter

### ISSUE THREAD

**Issue by Snailedlt** [Snailedlt/Markdown-Videos#54]
[ruff ](https://github.com/astral-sh/ruff) seems like the best python linter out there which can potentially be used as an autoformatter as well.
If not, [Black ](https://github.com/psf/black) might be the best autoformatter that's similar to prettier.

Once a linter and autoformatter is added the workflowscript to test the api can be updated to this:
```yml
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: Test with pytest
        run: |
          pytest -v

```

Based on: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow

`requirements.txt` also needs to be updated with the linter and autoformatter that is chosen
