### ISSUE TITLE
Only run tests when relevant folders are updated

### ISSUE THREAD

**Issue by Snailedlt** [Snailedlt/Markdown-Videos#81]
## Why?
Tests take a while to run. To make PR's faster tests should only run when relevant files are changed.
This depends on adding all relevant files into a single folder, which will be done as a part of #73 

## How?

https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo

```yml
on:
  push:
    paths:
    - 'sub-project/**'
```
